- libimageviewer/unionimage/unionimage.cpp
Log:
sync from https://salsa.debian.org/pkg-deepin-team/deepin-image-editor/-/blob/master/debian/patches/uniontech0001-chore-spelling-error-fix.patch
> chore: spelling error fix

- libimageviewer/viewpanel/contents/bottomtoolbar.cpp
- libimageviewer/viewpanel/contents/imgviewwidget.cpp
Description: 窗口最小时候UI适配,且缩略图最小显示1个
Log: 窗口最小时候UI适配,且缩略图最小显示1个
Bug: https://pms.uniontech.com/bug-view-130391.html
> fix: 修复bug130391

- libimageviewer/viewpanel/viewpanel.cpp
- libimageviewer/viewpanel/viewpanel.h
Description: 由于x11环境下存在切换normal状态却依然是最大化问题，需要自行记录窗口大小，从而修改
Log: 与窗口和删除有关
Bug: https://pms.uniontech.com/bug-view-137195.html
> fix: 修复bug137195

- libimageviewer/movieservice.cpp
- libimageviewer/movieservice.h
添加C-Style接口获取视频缩略图
Log: 添加C-Style接口获取视频缩略图
> feat: 添加C-Style接口获取视频缩略图

- debian/changelog
- debian/control
- libimageviewer/CMakeLists.txt
- libimageviewer/service/gstreamervideothumbnailer.cpp
- libimageviewer/service/gsttransplant.h
动态加载gstreamer，不再强制依赖
Log: 动态加载gstreamer，不再强制依赖
> feat: 动态加载gstreamer，不再强制依赖

- libimageviewer/movieservice.cpp
- libimageviewer/movieservice.h
增加基于JSON的视频信息获取接口
Log: 增加基于JSON的视频信息获取接口
> feat: 增加基于JSON的视频信息获取接口

- libimageviewer/widgets/extensionpanel.h
> feat: 创建依赖topic仓库

- debian/changelog
修改版本号以打包出适合topic仓库的版本
Log: 修改change log的版本号
> fix: 修改change log的版本号

- libimageviewer/movieservice.cpp
原因是部分数据位于mediainfo的全局区，而视频数据区不存在这些数据
解决方法是这部分数据改为预先读视频数据区，读取失败再去全局区寻找
Log: 修复部分视频数据读取失败
Bug: https://pms.uniontech.com/bug-view-152221.html
> fix: 修复部分视频数据读取失败

- libimageviewer/unionimage/unionimage.cpp
Description: FreeImage库中的FreeImage_TagToString()函数非多线程安全，多线程调用此静态函数时，有概率导致内存访问错误。修改为在调用FreeImage_TagToString()时加锁保护。
Log: 修复使用看图打开系统壁纸默认图片时，看图闪退
Bug: https://pms.uniontech.com/bug-view-156409.html
Influence: 图片加载
> fix: 修复使用看图打开系统壁纸默认图片时，看图闪退

- debian/control
- libimageviewer/movieservice.cpp
- libimageviewer/movieservice.h
- libimageviewer/service/ffmpegvideothumbnailer.cpp
- libimageviewer/service/ffmpegvideothumbnailer.h
- libimageviewer/service/gstreamervideothumbnailer.cpp
在aarch64下添加额外的视频缩略图解析方式
Log: 在aarch64下添加额外的视频缩略图解析方式
> fix: 在aarch64下添加额外的视频缩略图解析方式

- .reuse/dep5
Description: REUSE整改，testqrc下媒体文件使用CC-BY-4.0
Log: REUSE整改，testqrc下媒体文件使用CC-BY-4.0
> fix: REUSE整改，testqrc下媒体文件使用CC-BY-4.0

- libimageviewer/service/imagedataservice.cpp
原因是直接使用的常规手段暴力读取图片，导致在图片放大时失真
修改方法是改为使用SVG库读取并直接绘制到合适的尺寸以避免失真
Log: 修复底部栏SVG缩略图画质低
Bug: https://pms.uniontech.com/bug-view-164807.html
> fix: 修复底部栏SVG缩略图画质低

- libimageviewer/viewpanel/contents/bottomtoolbar.cpp
> fix: 释放测试代码

- debian/changelog
Update version to 1.0.25
Log: Update version to 1.0.25
> chore: Update version to 1.0.25

- debian/changelog
Update version to distinguish pro/community.
Log: Update version to 1.0.26
> chore: Update version to 1.0.26

- debian/changelog
Update version to 1.0.27
Log: Update version to 1.0.27
Bug: https://pms.uniontech.com/bug-view-157033.html
> chore: Update version to 1.0.27

- libimageviewer/viewpanel/contents/bottomtoolbar.cpp
修复看图应用删除图片无效的问题
Log: 修复看图应用删除图片无效的问题
Bug: https://pms.uniontech.com/bug-view-197551.html
> fix: 修复看图应用删除图片无效的问题

- debian/changelog
Update version to 1.0.28
相关PR：
* #70
* #71
* #72
Log: Update version to 1.0.28
Bug: https://pms.uniontech.com/bug-view-156711.html
Bug: https://pms.uniontech.com/bug-view-170707.html
Bug: https://pms.uniontech.com/bug-view-197551.html
> chore: Update version to 1.0.28

- debian/changelog
Update version to 1.0.29(community)
Log: Update version to 1.0.29(community)
> chore: Update version to 1.0.29(community)

- debian/changelog
Update version to 1.0.30
相关PR:
* linuxdeepin#75
* linuxdeepin#76
* linuxdeepin#77
Log: Update version to 1.0.30
Bug: https://pms.uniontech.com/bug-view-197551.html
Bug: https://pms.uniontech.com/bug-view-194689.html
> chore: Update version to 1.0.30

- debian/changelog
Update version to 1.0.31(Community)
Log: Update version to 1.0.31(Community)
> chore: Update version to 1.0.31(Community)

- libimageviewer/viewpanel/navigationwidget.cpp
- libimageviewer/viewpanel/viewpanel.cpp
1.关闭按钮右上角对齐，间距5px
2.导航窗口左下对齐，间距10px
3.遮罩框添加白色描边
Log: 【UI】导航窗口样式调整
Bug: https://pms.uniontech.com/bug-view-194661.html
> fix: 【UI】导航窗口样式调整

- debian/changelog
修复UI问题：
1. 重命名弹窗样式调整
2. 导航窗口样式调整 相关PR如下：
* https://github.com/linuxdeepin/image-editor/pull/80
* https://github.com/linuxdeepin/image-editor/pull/81
Log: Update version to 1.0.32
> chore: Update version to 1.0.32

- libimageviewer/imageviewer.cpp
- libimageviewer/imageviewer.h
- libimageviewer/viewpanel/scen/imagegraphicsview.cpp
Update REUSE date
Log: Update REUSE date
> chore: Update REUSE date

- debian/changelog
相关PR:
* #99
Log: Update version to 1.0.38
> chore: Update version to 1.0.38

- libimageviewer/service/aimodelservice.cpp
- libimageviewer/service/aimodelservice.h
- libimageviewer/translations/libimageviewer.ts
- libimageviewer/translations/libimageviewer_zh_CN.ts
- libimageviewer/translations/libimageviewer_zh_HK.ts
- libimageviewer/translations/libimageviewer_zh_TW.ts
添加文件不可保存的提示对话框.
Log: 补充错误提示信息.
Change-Id: Ib66781fc1d9bc7eee32fdf04472a7d2c1b6020d1
> fix: Add file unsavable notify dialog.

- libimageviewer/imageengine.cpp
- libimageviewer/imageengine.h
- libimageviewer/imageviewer.cpp
- libimageviewer/imageviewer.h
- libimageviewer/service/permissionconfig.cpp
- libimageviewer/service/permissionconfig.h
- libimageviewer/viewpanel/viewpanel.cpp
- libimageviewer/viewpanel/viewpanel.h
- tests/test_permissionconfig.cpp
修复一处在低版本的编译错误,
修复cppcheck错误。
Log: 修复一处编译错误和cppcheck错误
> fix: Build error and cppcheck error

- libimageviewer/service/permissionconfig.cpp
- libimageviewer/service/permissionconfig.h
修复低版本下 DPrintPreviewDialog 接口差异
导致构建失败.
Log: 修复一处构建问题
> fix: Build error with DPrintPreviewDialog

- libimageviewer/service/permissionconfig.cpp
- libimageviewer/service/permissionconfig.h
- libimageviewer/widgets/printhelper.cpp
修复低版本下不存在 dprintpreviewsettinginfo 导致的
编译兼容问题.
dtk 未提供此类, 使用 DWaterMarkHelper 进行限制
Log: 修复一处编译问题
> fix: Build error with printsettinginfo

- libimageviewer/widgets/printhelper.cpp
> fix: Remove not compatible header file.

- libimageviewer/unionimage/imageutils.cpp
- libimageviewer/viewpanel/viewpanel.cpp
之前设计的缓存目录名重复,在多实例下, 其它实例退出
会导致缓存目录被误删除. 调整缓存目录设计,改到/tmp
目录且每个实例唯一.
Log: 修复误删除缓存目录的问题
Bug: https://pms.uniontech.com/bug-view-247289.html
Influence: SetWallpaper
> fix: Wrong clean cache folder

- .tx/config
- CMakeLists.txt
- libimageviewer/CMakeLists.txt
- libimageviewer/image-viewer_global.h
- libimageviewer/quickprint.h
- libimageviewer/quickprint/printimageloader.cpp
- libimageviewer/quickprint/printimageloader.h
- libimageviewer/quickprint/quickprint.cpp
- libimageviewer/quickprint/quickprint_p.h
- libimageviewer/service/mtpfileproxy.cpp
- libimageviewer/service/mtpfileproxy.h
- libimageviewer/service/permissionconfig.cpp
- libimageviewer/translations/libimageviewer.ts
- libimageviewer/translations/libimageviewer_bo.ts
- libimageviewer/translations/libimageviewer_ug.ts
- libimageviewer/translations/libimageviewer_zh_CN.ts
- libimageviewer/translations/libimageviewer_zh_HK.ts
- libimageviewer/translations/libimageviewer_zh_TW.ts
- libimageviewer/unionimage/baseutils.cpp
- libimageviewer/unionimage/baseutils.h
- libimageviewer/unionimage/unionimage.cpp
- tests/test_quickprint.cpp
> feat: 添加批量打印功能

- libimageviewer/service/commonservice.h
- libimageviewer/service/imagedataservice.cpp
- libimageviewer/service/imagedataservice.h
- libimageviewer/viewpanel/contents/bottomtoolbar.cpp
- libimageviewer/viewpanel/contents/bottomtoolbar.h
- libimageviewer/viewpanel/contents/imgviewwidget.h
- libimageviewer/viewpanel/viewpanel.cpp
调整图像加载策略,缩略图以实际显示区域动态计算,
而非固定数据长度.
移除无关代码,修改一处创建线程未及时释放.
Log: 修复部分启动问题
> fix: Improve image load policy

- debian/changelog
Bump version to 1.0.45
Log: Bump version to 1.0.45
> chore: Bump version to 1.0.45

- libimageviewer/viewpanel/scen/imagegraphicsview.cpp
修复看图ftp共享目录图片打开显示空白
Bug: https://pms.uniontech.com/bug-view-275425.html
Log: 修复看图ftp共享目录图片打开显示空白
> fix: 修复看图ftp共享目录图片打开显示空白

- libimageviewer/CMakeLists.txt
fix security compile
Bug: https://pms.uniontech.com/bug-view-296989.html
Log: fix security compile
> fix: fix security compile

- libimageviewer/unionimage/unionimage.cpp
修复查看750 X 7882尺寸图片问题
Bug: https://pms.uniontech.com/bug-view-310713.html
Log: 修复查看750 X 7882尺寸图片问题
> fix: 修复查看750 X 7882尺寸图片问题
