libimageviewer/widgets/printhelper.cpp, tests/CMakeLists.txt
Description: dialog在wayland下的情况和x11不同,需要指定父指针
Log: 与打印有关
Bug: https://pms.uniontech.com/bug-view-136767.html
=> fix: 修复bug136767

libimageviewer/service/imagedataservice.cpp, libimageviewer/service/imagedataservice.h, libimageviewer/viewpanel/viewpanel.cpp
从日志上看是图片加载队列炸了
目前修改为当界面退出时停止全部加载队列，重新进入界面后再重启队列
Log: 尝试修复频繁进入退出导致的崩溃
Bug: https://pms.uniontech.com/bug-view-135425.html
=> fix: 尝试修复频繁进入退出导致的崩溃

libimageviewer/unionimage/unionimage.h, libimageviewer/viewpanel/scen/imagegraphicsview.cpp, libimageviewer/viewpanel/viewpanel.cpp
Description: 修复看图因为切换图片导致内存上涨不降的问题，由于每次发送缩略图变更是发送的原图，所以导致内存居高不下
Log: 修复看图因为切换图片导致内存上涨不降的问题
Bug: https://pms.uniontech.com/bug-view-137831.html
=> fix: 修复看图因为切换图片导致内存上涨不降的问题

libimageviewer/service/imagedataservice.cpp, libimageviewer/viewpanel/viewpanel.cpp, tests/gtestview.cpp
原因是单元测试中存在主动析构单例的代码，导致最近新加的部分代码崩溃
解决方法是删除这部分代码
Log: 修复单元测试崩溃
=> fix: 修复单元测试崩溃

libimageviewer/service/imagedataservice.cpp, libimageviewer/viewpanel/scen/imagegraphicsview.cpp
Description: 修复bug138877,由于刷新的时候尺寸有问题的图片直接变为撕裂图了,现在裁剪为200,200
Log: 与裁剪有关
Bug: https://pms.uniontech.com/bug-view-138877.html
=> fix: 修复bug138877

libimageviewer/viewpanel/viewpanel.cpp, libimageviewer/viewpanel/viewpanel.h
Description: 在多屏下，由于无桌面工具栏，窗口在全屏和最大化时控件大小未变更，旧版代码没有捕获大小变更事件，导致未处理标题栏隐藏，添加事件过滤捕获窗口状态变更事件，主动隐藏标题栏。
Log: 修复看图先最大化再切换至全屏，鼠标唤起工具栏的时候也会唤起顶部标题栏
Bug: https://pms.uniontech.com/bug-view-124991.html
Influence: 标题栏
=> fix: 修复看图先最大化再切换至全屏，鼠标唤起工具栏的时候也会唤起顶部标题栏

debian/control, libimageviewer/CMakeLists.txt, libimageviewer/movieservice.cpp, libimageviewer/movieservice.h, libimageviewer/service/gstreamervideothumbnailer.cpp, libimageviewer/service/gstreamervideothumbnailer.h
1.添加mediainfo作为主要的视频基础数据解析库，ffmpeg命令行为备用库
2.添加gstreamer作为主要的视频缩略图解析库，ffmpegthumbnailer命令行为备用库
Log: 添加双引擎视频解析库以解决缩略图不一致和速度慢
Bug: https://pms.uniontech.com/bug-view-129569.html
=> fix: 添加双引擎视频解析库以解决缩略图不一致和速度慢

debian/rules
高版本的cmake不再支持--parallel和--buildsystem参数，直接移除
Log: 适配高版本cmake
=> fix: 适配高版本cmake

tests/test_movieservice.cpp
未知原因导致解析失败，但是GStreamer方案可以解析成功，目前删除对应的用例
该用例成功或者失败不影响相册的相关功能
Log: 修复部分机型下ffmpegthumbnailer无法解析测试用例视频导致单元测试失败
Bug: https://pms.uniontech.com/bug-view-146493.html
=> fix: 修复部分机型下ffmpegthumbnailer无法解析测试用例视频导致单元测试失败

libimageviewer/viewpanel/viewpanel.cpp
Description: 仅在全屏时，关闭打印窗口后，开启定时器，三秒后隐藏鼠标
Log: 修复【PGV】【相册】相册中选择图片点击导出后，鼠标光标在相册界面不可见的问题
Bug: https://pms.uniontech.com/bug-view-147995.html
=> fix: 修复【PGV】【相册】相册中选择图片点击导出后，鼠标光标在相册界面不可见的问题

libimageviewer/viewpanel/viewpanel.cpp
Description: 若为模态窗口，不隐藏鼠标
Log: 解决模态窗口显示下，全屏图片不能显示鼠标的问题
Bug: https://pms.uniontech.com/bug-view-147995.html
=> fix: 解决模态窗口显示下，全屏图片不能显示鼠标的问题

debian/libimageeditor-dev.install, debian/libimageeditor.install
文管组拒绝使用自动搜索.so的代码，此处将在安装主包的时候将不带版本号的.so安装进去
Log: 照顾一下文管的.so搜索机制
=> fix: 照顾一下文管的.so搜索机制

libimageviewer/libimageviewer.pc.in, libimagevisualresult/libimagevisualresult.pc.in
1. 完善文件路径
2. 补充 -L 参数
3. QtSvg -> Qt5Svg
4. 删除pkgconfig对 Qt5LinguistTools  freeimage 的检查
https://bugzilla.redhat.com/show_bug.cgi?id=1471417
https://sourceforge.net/p/freeimage/feature-requests/57/
Qt5LinguistTools  freeimage 的上游应该没有提供 .pc 文件
=> fix: use correct LIBDIR for pkgconfig

.reuse/dep5, 3rdparty/tiff-tools/converttiff.h, 3rdparty/tiff-tools/tiffcp.c, LICENSES/libtiff.txt, README.md, README.zh_CN.md, debian/control, debian/copyright, libimageviewer/CMakeLists.txt, libimageviewer/unionimage/imageutils.cpp, libimageviewer/unionimage/imageutils.h, libimageviewer/unionimage/unionimage.cpp, libimageviewer/viewpanel/viewpanel.cpp, tests/CMakeLists.txt
Description: 未能读取的tif文件为ojpeg压缩格式，底层libtiff库默认不支持此格式，无法正常读取。对使用ojpeg压缩格式或读取异常的图片，尝试转换文件压缩格式，并将转换后的文件放入缓存目录，正常展示tif文件数据。 添加libtiff-dev库构建依赖，修改README及相关版权信息。
Log: 修复tif和tiff格式的图片无法在本地打开
Bug: https://pms.uniontech.com/bug-view-160951.html
Influence: tif文件读取
=> fix: 修复tif和tiff格式的图片无法在本地打开

libimageviewer/unionimage/imageutils.cpp
在部分图片的设置壁纸选项的显示上，文管和看图/相册不一致
目前直接同步文管的壁纸设置策略，做到两边显示一致
Log: 同步文件管理器的壁纸设置策略
Bug: https://pms.uniontech.com/bug-view-163869.html
=> fix: 同步文件管理器的壁纸设置策略

libimageviewer/viewpanel/scen/graphicsitem.cpp
在快速缩放下，部分动图会出现奇怪的显示结果
目前修改为和静态图保持一致，使用平滑缩放进行显示
Log: 修改动图显示为平滑缩放模式
Bug: https://pms.uniontech.com/bug-view-154885.html
=> fix: 修改动图显示为平滑缩放模式

.tx/deepin.conf, debian/changelog, libimageviewer/movieservice.cpp, libimageviewer/movieservice.h, libimageviewer/unionimage/baseutils.cpp, libimageviewer/unionimage/baseutils.h, libimageviewer/viewpanel/contents/bottomtoolbar.cpp, libimageviewer/viewpanel/contents/bottomtoolbar.h, libimageviewer/viewpanel/viewpanel.cpp
原因是未对deepin-ocr的安装情况作判断
解决方法是检测deepin-ocr命令是否可用，当不可用时即判定为未安装deepin-ocr，或相关功能损坏，此时即隐藏按钮
Log: 修复未安装deepin-ocr时，相关按钮仍然显示出来
Bug: https://pms.uniontech.com/bug-view-159241.html
=> fix: 修复未安装deepin-ocr时，相关按钮仍然显示出来

libimageviewer/unionimage/unionimage.cpp
Description: 使用Q_GLOBAL_STATIC宏的方式存在错误，未构造单例对象，exists()持续返回false，未正常读取图片数据。修改使用方式，保证多线程安全下，构造单实例对象。
Log: 修复图片信息偶现没有拍摄日期等信息
Bug: https://pms.uniontech.com/bug-view-185337.html
Influence: 获取图片元数据
=> fix: 修复图片信息偶现没有拍摄日期等信息

libimageviewer/viewpanel/contents/imageinfowidget.cpp, libimageviewer/viewpanel/contents/imageinfowidget.h, libimageviewer/viewpanel/viewpanel.cpp, libimageviewer/viewpanel/viewpanel.h
Description: 原因是图片在切换和加载完成后触发了两次菜单刷新操作，
导致界面重复刷新。图片在切换和加载完成后所取得的详细信息是一致的。
修改为根据数据变更刷新详细信息，且保留强制刷新的功能。
Log: 修复切换图片查看时，图片信息刷新两次的问题
Bug: https://pms.uniontech.com/bug-view-175369.html
Influence: 图片信息
=> fix: 修复切换图片查看时，图片信息刷新两次的问题

libimageviewer/widgets/printhelper.cpp
图片打印时仅设置图片名，且后缀为pdf。
修改为完整路径，以便cups服务获取准确打印信息。
Log: 修复打印图片时无图片路径信息的问题
Bug: https://pms.uniontech.com/bug-view-188457.html
Influence: DTK5.4.10以上的图片打印
=> fix: 修复打印图片时无图片路径信息的问题

libimageviewer/imageengine.h, libimageviewer/viewpanel/contents/bottomtoolbar.cpp
添加显示删除确认弹窗的处理流程，同步修改相册代码
Log: 修复相册-大图模式删除图片，没有显示删除确认弹窗的问题
Bug: https://pms.uniontech.com/bug-view-157033.html
=> fix: 修复相册-大图模式删除图片，没有显示删除确认弹窗的问题

libimageviewer/viewpanel/viewpanel.cpp
【UI】底栏边距调整，与工具栏按钮间隙保持一致
Log:  【UI】底栏边距调整，与工具栏按钮间隙保持一致
Bug: https://pms.uniontech.com/bug-view-156711.html
=> chore: 【UI】底栏边距调整，与工具栏按钮间隙保持一致

libimageviewer/viewpanel/viewpanel.cpp, libimageviewer/viewpanel/viewpanel.h
对于不支持设为壁纸的图片，置灰设置壁纸菜单项
Log: 对于不支持设为壁纸的图片，置灰设置壁纸菜单项
Bug: https://pms.uniontech.com/bug-view-170707.html
=> feat: 对于不支持设为壁纸的图片，置灰设置壁纸菜单项

libimageviewer/widgets/renamedialog.cpp
修复重名提示时，输入框未标红的问题
Log: 修复重名提示时，输入框未标红的问题
Bug: https://pms.uniontech.com/bug-view-194689.html
=> fix: 修复重名提示时，输入框未标红的问题

libimageviewer/unionimage/imageutils.cpp, libimageviewer/viewpanel/viewpanel.cpp
用看图打开图片时，会判断是否置灰设为壁纸菜单项，需要对返回的设为壁纸菜单项做判空处理
Log: 修复打开看图闪退的问题
=> fix: 修复打开看图闪退的问题

libimageviewer/imageengine.h, libimageviewer/viewpanel/contents/bottomtoolbar.cpp
大图-删除按钮处理流程整理：
1.看图-大图删除按钮：直接删除图片
2.相册-大图删除按钮：
a.老版本，直接删除图片，保持和看图逻辑一致
b.新版本，弹出删除确认弹窗
deepin-album相关pr:
https://github.com/linuxdeepin/deepin-album/pull/155
Log: 修复低版本相册点击大图-删除按钮无效的问题
=> fix: 修复低版本相册点击大图-删除按钮无效的问题

libimageviewer/widgets/renamedialog.cpp
1.按钮间距20px
2.调整文案与顶部间距
3.调整中间竖线间距20px, 样式变为浅灰
Log: 【UI】重命名弹窗样式调整
Bug: https://pms.uniontech.com/bug-view-194651.html
=> fix: 【UI】重命名弹窗样式调整

libimageviewer/viewpanel/viewpanel.cpp, libimageviewer/widgets/toptoolbar.cpp
DTK 在 5.6.4 版本提供紧凑模式,看图适配紧凑模式,
动态调整标题栏高度和位置.
* 新增接口,需兼容性检查
Log: Adapt compact mode.
Bug: https://pms.uniontech.com/bug-view-199309.html
Influence: TitleBar CompactMode
=> fix: Adapt compact mode.

libimagevisualresult/src/utils.h
GCC 13 no longer includes cstdint in all cases and code is supposed to handle this
Fixes build fails like:
[   96s] In file included from /home/abuild/rpmbuild/BUILD/image-editor-1.0.19/libimagevisualresult/src/lut.cpp:22:
[   96s] /home/abuild/rpmbuild/BUILD/image-editor-1.0.19/libimagevisualresult/src/utils.h:8:33: error: 'uint8_t' was not declared in this scope
[   96s]     8 | typedef std::vector<std::vector<uint8_t>>       lutData;
[   96s]       |                                 ^~~~~~~
=> Fix build using gcc13: add missing include cstdint

debian/changelog
Update version to 1.0.33
适配紧凑模式，修复gcc13版本编译问题。
相关PR：
* https://github.com/linuxdeepin/image-editor/pull/84
Log: Update version to 1.0.33
=> chore: Update version to 1.0.33

libimageviewer/unionimage/unionimage.cpp, libimageviewer/viewpanel/viewpanel.cpp
1. 管控图片读取时,返回图片但文件不可读取,
二次确定图片类型时可读取列表为空,未进行边界判断,
添加列表边界判断处理.
2. 保存图片文件时默认按最高质量存储,调整为默认值,
以在保留质量的情况下降低磁盘使用率.
=> fix: 修复图片读取和保存图片的问题

debian/changelog
Update version to 1.0.34
相关PR：
* https://github.com/linuxdeepin/image-editor/pull/86
Log: Update version to 1.0.34
=> chore: Update version to 1.0.34

debian/control, libimageviewer/CMakeLists.txt, libimageviewer/imageviewer.cpp, libimageviewer/service/mtpfileproxy.cpp, libimageviewer/service/mtpfileproxy.h, libimageviewer/viewpanel/contents/imageinfowidget.cpp, libimageviewer/viewpanel/scen/imagegraphicsview.cpp, libimageviewer/viewpanel/viewpanel.cpp
使用基础IO接口操作gvfs-mtp挂载的文件时,由于多次转发,IO效率较低,
引入dfm-io,使用gio接口操作,改进IO性能.
Log: 引入dfm-io加快gvfs-mtp挂载文件读取.
Bug: https://pms.uniontech.com/bug-view-204243.html
Influence: FileLoad MTP
=> fix: Read images from gvfs-mtp mounted folder was slow.

libimageviewer/service/ffmpegvideothumbnailer.cpp
Log:
When loading the library, QLibrary searches in all the system-specific library locations (e.g. LD_LIBRARY_PATH on Unix), unless the file name has an absolute path.
for linux, will use dlopen in QLibrary： https://man7.org/linux/man-pages/man3/dlopen.3.html
=> feat: just use QLibrary to search .so

debian/control, libimageviewer/CMakeLists.txt, libimageviewer/imageviewer.cpp, libimageviewer/imageviewer.h, libimageviewer/service/mtpfileproxy.cpp, libimageviewer/service/mtpfileproxy.h, libimageviewer/viewpanel/contents/imageinfowidget.cpp, libimageviewer/viewpanel/scen/imagegraphicsview.cpp, libimageviewer/viewpanel/viewpanel.cpp
使用基础IO接口操作gvfs-mtp挂载的文件时,由于多次转发,IO效率较低,
引入dfm-io,使用gio接口操作,改进IO性能.
dfm-io 构建依赖引入'|'(或)关系，允许在不同环境中编译，
当环境中不存在 libdfm-io-dev 时，将不会使用 dfm-io 拷贝优化。
引入的 qttools5-private-dev 不会引入其它安装依赖；
注意：后续环境或 control 文件变化导致 qttools5-private-dev
已被安装而不安装 libdfm-io-dev.
Log: 引入dfm-io加快gvfs-mtp挂载文件读取.
Bug: https://pms.uniontech.com/bug-view-204243.html
已在拉取分支 project/dfm-io 验证
=> fix: Read images from gvfs-mtp mounted folder was slow. 

debian/changelog
Bump version to 1.0.35
PR:
* https://github.com/linuxdeepin/image-editor/pull/90
* https://github.com/linuxdeepin/image-editor/pull/92
Log: Bump version to 1.0.35
=> chore: Bump version to 1.0.35

libimageviewer/movieservice.cpp, libimageviewer/service/ffmpegvideothumbnailer.cpp
软件调整环境变量,可能未查找到库,解析接口时,
遗漏判空处理,导致访问越界;
同时调整创建临时图片的方式,改为 QTemporaryDir 的方式.
Log: 修复未查找到ffmpeg依赖包时崩溃的问题
Bug: https://pms.uniontech.com/bug-view-213565.html
Influence: MovieCover
=> fix: Crash when not found libffmpegthumbnailer.so

debian/changelog
Bump version to 1.0.36
PR:
* https://github.com/linuxdeepin/image-editor/pull/93
Log: Bump version to 1.0.36
=> chore: Bump version to 1.0.36

debian/changelog
Bump version to 1.0.37 for community,
previous is 1.0.34
PR:
* https://github.com/linuxdeepin/image-editor/pull/90
* https://github.com/linuxdeepin/image-editor/pull/92
* https://github.com/linuxdeepin/image-editor/pull/93
Log: [ Community ] Bump version to 1.0.37
=> chore: [ Community ] Bump version to 1.0.37

libimageviewer/viewpanel/viewpanel.cpp, libimageviewer/widgets/toptoolbar.cpp
旧版使用DTK版本号判断是否开启紧凑模式编译.
但在dtkcore高版本,dtkgui低版本的情况下,
会导致进入编译代码,但不存在紧凑模式接口,
编译失败.
Log: 修复在低版本dtkgui构建失败问题.
Influence: CompactMode
Change-Id: I94598866cbf305a9596b47d124991bee96ffd538
=> fix: compact mode build faild on low dtkgui version.

libimageviewer/service/aimodelservice.cpp, libimageviewer/viewpanel/contents/imgviewlistview.cpp, libimageviewer/viewpanel/scen/imagegraphicsview.cpp, libimageviewer/viewpanel/scen/imagegraphicsview.h, libimageviewer/viewpanel/viewpanel.cpp, libimageviewer/viewpanel/viewpanel.h
1. 初始化时多线程加载图片信息，在低性能机型上， 获取首张缩略图信息时，图片全加载信息还未更新， 仅取得图片大小，因此在设置缩略图时， 若内部图片类型为空，手动更新图片类型；
2. 打印过程中屏蔽拖拽切换图片接口；
3. 优化界面，调整打印信息。
Log: 修复部分问题
Bug: https://pms.uniontech.com/bug-view-232295.html
Bug: https://pms.uniontech.com/bug-view-232301.html
Influence: InitImageType DragImage
Change-Id: Ifb21d78859fe2d43777ecb9b61ee0414477c4cd5
=> fix: Init type error / disable drag in processing.

libimageviewer/viewpanel/viewpanel.cpp
右键菜单项使用增强后图像而不是使用原始图像,
涉及保存/打印/幻灯片放映选项,幻灯片放映开始时
提示是否保存AI增强图像.
Log: 修复右键菜单项使用增强图像,而不是原始图像.
Bug: https://pms.uniontech.com/bug-view-232505.html
Influence: Menu
=> fix: Action using enhance image instead of source.

libimageviewer/viewpanel/contents/aienhancefloatwidget.cpp, libimageviewer/viewpanel/contents/aienhancefloatwidget.h, libimageviewer/viewpanel/viewpanel.cpp
* 展示AI增强图像时,屏蔽相册相关菜单项.
* 统一底部栏和侧边图像增强栏的颜色.
Log: 展示AI增强图像时,屏蔽相册相关菜单项.
Bug: https://pms.uniontech.com/bug-view-232505.html
Influence: Menu
=> fix: Disable action using enhance image instead of source. 

libimageviewer/viewpanel/contents/aienhancefloatwidget.cpp
在更新AI增强服务界面时,使用DTK 5.4 版本之后引入的
DPaletteHelper 接口,和低版本不兼容.
Log: 修复部分问题
Change-Id: Ie796c06c6c23bc92318ddbcf45fbb1d7dd3462cb
=> fix: Build error on low dtk version.

debian/changelog
Bump version to 1.0.40
PR:
* https://github.com/linuxdeepin/image-editor/pull/111
Log: Bump version to 1.0.40
Change-Id: Ieb7c73c9cccb42dfa5b93b953a5e489aba0572df
=> chore: Bump version to 1.0.40

libimageviewer/viewpanel/contents/bottomtoolbar.cpp, libimageviewer/viewpanel/contents/imgviewlistview.cpp
旧版看图存在多种取得当前图片的接口,
删除图片文件使用的接口所指向的文件路径
变量在重命名后未更新.
调整取得当前图片路径的接口,和其它代码
保持一致.同时更新重命名后当前图片路径
变量用于其它内部处理获取正确信息.
Log: 修复重命名后删除图片无响应.
Bug: https://pms.uniontech.com/bug-view-236589.html
Influence: Delete
Change-Id: I1e54f3f289e3d88ec84afed686ad16bd0137a73f
=> fix: Delete image not work after rename.

debian/changelog
Bump version to 1.0.41
PR:
* https://github.com/linuxdeepin/image-editor/pull/113
Log: Bump version to 1.0.41
Change-Id: I2810650f972d751b0a14535b8e9b25ca29329a71
=> chore: Bump version to 1.0.41

.tx/config, .tx/deepin.conf, CMakeLists.txt, libimageviewer/imageengine.cpp, libimageviewer/imageengine.h, libimageviewer/imageviewer.cpp, libimageviewer/service/permissionconfig.cpp, libimageviewer/service/permissionconfig.h, libimageviewer/translations/libimageviewer.ts, libimageviewer/translations/libimageviewer_es.ts, libimageviewer/translations/libimageviewer_zh_CN.ts, libimageviewer/unionimage/baseutils.cpp, libimageviewer/viewpanel/contents/bottomtoolbar.cpp, libimageviewer/viewpanel/scen/imagegraphicsview.cpp, libimageviewer/viewpanel/viewpanel.cpp, libimageviewer/viewpanel/viewpanel.h, libimageviewer/widgets/printhelper.cpp, libimageviewer/widgets/printhelper.h, tests/CMakeLists.txt, tests/test_permissionconfig.cpp
合并权限控制和水印需求到主线.
涉及提交 https://github.com/linuxdeepin/image-editor/commit/807a3b3a84d6c76e60d8fa216229dbdfd04ea732
到 https://github.com/linuxdeepin/image-editor/commit/31bae041cdaad3045fe8d15f33b4d0d9cc8751fd
* 新增权限控制功能, 允许配置功能开闭;
* 新增水印功能, 允许通过配置定制阅读和打印水印;
* 水印接口特殊, DTKWidget主线和定制线的接口不同.
Log: 回合看图权限控制和水印需求
Task: https://pms.uniontech.com/story-view-27785.html
Task: https://pms.uniontech.com/story-view-30217.html
Influence: Print Permission
=> feat: Merge permission/watermark into master

libimageviewer/viewpanel/contents/imgviewdelegate.cpp, libimageviewer/widgets/renamedialog.cpp, libimageviewer/widgets/renamedialog.h
看图略缩图预览显示调整, paint()中绘制缩略图
仅显示中间部分图像,其他部分裁剪.
Log: 修复了预览略缩图拉伸bug
Bug: https://pms.uniontech.com/bug-view-158423.html
修改了重命名窗口的文件名后缀颜色，添加了其主题变更的颜色变化
Log: 修复了深色模式下重命名弹窗文字看不清的问题
Bug: https://pms.uniontech.com/bug-view-231485.html
=> 修复UI问题 Fix 158423 231485

libimageviewer/unionimage/baseutils.cpp, libimageviewer/unionimage/baseutils.h, libimageviewer/viewpanel/viewpanel.cpp
拷贝较大图片向剪贴板写入数据时，可能造成卡顿，
缩放图片，且仅在 wayland 环境下调用
Log: 修复一处拷贝可能卡顿的问题
=> fix: Copy may cause program lag

libimageviewer/unionimage/baseutils.cpp
回退拷贝图像数据的修改，会导致 1070 wayland
下拷贝无图片显示，仅在定制分支保留
Log: 回退拷贝图像数据的修改
=> fix: Revert setImageData on copy

libimageviewer/viewpanel/viewpanel.cpp, libimageviewer/viewpanel/viewpanel.h
The top toolbar shadow of the homepage is different from the one of the imageview while the first one is thicker.
Log: add a widget to make the top boolbar shadow thicker
Bug: https://pms.uniontech.com/bug-view-156727.html
=> fix: The top toolbar background shading is inconsistent

debian/changelog
Bump version to 1.0.42
PR:
* https://github.com/linuxdeepin/image-editor/pull/115
* https://github.com/linuxdeepin/image-editor/pull/119
* https://github.com/linuxdeepin/image-editor/pull/122
* https://github.com/linuxdeepin/image-editor/pull/123
* https://github.com/linuxdeepin/image-editor/pull/124
* https://github.com/linuxdeepin/image-editor/pull/125
* https://github.com/linuxdeepin/image-editor/pull/126
Log: Bump version to 1.0.42
=> chore: Bump version to 1.0.42

libimageviewer/imageviewer.cpp, libimageviewer/unionimage/baseutils.cpp, libimageviewer/unionimage/baseutils.h, libimageviewer/viewpanel/contents/imageinfowidget.cpp, libimageviewer/viewpanel/contents/imageinfowidget.h
Wayland 下默认动画和应用动画重叠，同时可能导致
wayland 未正确取得控件信息，显示花屏，调整应用
动画在 wayland 动画后.
* 尝试首次展示降低动画时间,或展示后show()刷新 效果不佳,控件重叠
Log: Info widget flicking on wayland
Bug: https://pms.uniontech.com/bug-view-242125.html
=> fix: Info widget flicking on wayland

debian/changelog
Bump version to 1.0.43
PR:
* https://github.com/linuxdeepin/image-editor/pull/128
Log: Bump version to 1.0.43
=> chore: Bump version to 1.0.43

libimageviewer/viewpanel/contents/bottomtoolbar.cpp
The bottom line of the bottombar bottoms is thick.
Log: The bottom line of the bottombar bottoms is thick.
Bug: https://pms.uniontech.com/bug-view-197857.html
=> fix: The bottom line of the bottombar bottoms is thick.

libimageviewer/unionimage/imageutils.cpp, libimageviewer/unionimage/imageutils.h, libimageviewer/viewpanel/viewpanel.cpp
设置壁纸时同时设置锁屏壁纸
Log: 设置壁纸时同时设置锁屏壁纸
Task: https://pms.uniontech.com/story-view-32367.html
Influence: SetWallpaper
=> feat: Set greeter background when setting wallpaper

libimageviewer/unionimage/imageutils.cpp, libimageviewer/viewpanel/viewpanel.cpp
设置锁屏背景的图片过大,后端DBus可能返回文件过大错误,
调整压缩格式PNG为JPG,同时过大的PNG/JPG图片也会被压缩.
Log: 修复设置大图片为壁纸无反应的问题
Bug: https://pms.uniontech.com/bug-view-247311.html
Influence: SetWallpaper
=> fix: Cached greeter background image too large

debian/changelog
Bump version to 1.0.44
PR:
* https://github.com/linuxdeepin/image-editor/pull/130
* https://github.com/linuxdeepin/image-editor/pull/131
* https://github.com/linuxdeepin/image-editor/pull/132
* https://github.com/linuxdeepin/image-editor/pull/133
chore: Bump version to 1.0.44
=> chore: Bump version to 1.0.44

libimageviewer/quickprint/printimageloader.cpp, libimageviewer/unionimage/unionimage.cpp, libimageviewer/viewpanel/scen/imagegraphicsview.cpp, libimageviewer/widgets/printhelper.cpp
禁用TIFF图片自动根据EXIF信息旋转；
且由于 libqtiff 插件缓存的旋转信息可能错误，
缓存数据会导致内存占用升高，调整为每次读取
TIFF图片数据。
Log: 调整TIFF图片默认展示效果
Influence: ImageView Print
=> feat: disable tiff picture auto transform

libimageviewer/unionimage/unionimage.cpp
add kimageformat-plugins for the qimage plugins
add the libavif-dev as heif file decoder. add the
libheif-dev as avif file decoder.
Log: add avif and heif image format file support
=> feat: add avif and heif image format file support

libimageviewer/unionimage/unionimage.cpp
修复漏洞 【CITIVD】Deepin-image-viewer-缓冲区溢出
Bug: https://pms.uniontech.com/bug-view-259819.html
Log: 修复漏洞 【CITIVD】Deepin-image-viewer-缓冲区溢出
=> fix: 修复漏洞 【CITIVD】Deepin-image-viewer-缓冲区溢出

libimageviewer/service/aimodelservice.cpp, libimageviewer/service/aimodelservice_p.h
Modify not to automatically create temporary directories.
* AIModelServiceData should not be created, but not fully tested.
Log: Not create temporary dirs by default
=> fix: temporary dirs are created by default

libimageviewer/unionimage/baseutils.cpp
remove bash use
Log: remove bash use
Task: https://pms.uniontech.com/task-view-362321.html
=> fix: [cmd] remove bash use

libimageviewer/CMakeLists.txt
Log: Using a special method is not friendly for other distributions
=> fix: Use common method to check the version of dtkwidget

libimageviewer/quickprint/printimageloader.cpp
As title.
Log: Support multi frame image load.
Influence: quickprint
=> fix: support multi frame image load

libimageviewer/service/ffmpegvideothumbnailer.cpp, tests/test_ffmpegvideothumbnailer.cpp
完善 initFFmpegVideoThumbnailer() ，添加备用的查找库方式
和提示信息。在 QLibrary 无法查找时尝试使用手动查找方式取得
其它版本的 libffmpegthumbnailer.so 动态库。
Log: 补充适配缩略图查找方式和UT
Bug: https://pms.uniontech.com/bug-view-213565.html
Bug: https://pms.uniontech.com/bug-view-221557.html
Influence: VideoThumbnailer
=> test: Add initFFmpegVideoThumbnailer unit test.

tests/gtestview.h, tests/test_ffmpegvideothumbnailer.cpp
abc-123.jpg is about to be deleted
Log: as title
=> test: update test image path

libimageviewer/quickprint/quickprint.cpp
适配103x编译
task: https://pms.uniontech.com/task-view-365161.html
Log: 适配103x编译
=> fix: 适配103x编译

debian/changelog, debian/control
[fix: Update build configuration and dependencies](https://github.com/linuxdeepin/image-editor/pull/161/commits/fa1fb15f87d219a58c36b5ea65a179e15e4d1745)
1. Updated comment from Qt5 to Qt6 support
2. Fixed libimageeditor6-dev dependency name
Log: Fix package build and installation
[chore: Bump version to 6.5.1](https://github.com/linuxdeepin/image-editor/pull/161/commits/29751a1b0f0359cebc53d52c9ea8373a7a9fb568)
Bump version to 6.5.1
Log: Bump version to 6.5.1
=> fix:  Depends error | chore: Bump version to 6.5.1

.gitignore, libimageviewer/quickprint/printimageloader.cpp, libimageviewer/quickprint/quickprint.cpp, libimageviewer/service/aimodelservice.cpp, libimageviewer/service/commonservice.cpp, libimageviewer/service/configsetter.cpp, libimageviewer/service/ffmpegvideothumbnailer.cpp, libimageviewer/service/imagedataservice.cpp, libimageviewer/service/mtpfileproxy.cpp, libimageviewer/service/permissionconfig.cpp, libimageviewer/slideshow/imageanimation.cpp, libimageviewer/slideshow/slideshowpanel.cpp, libimageviewer/unionimage/baseutils.cpp, libimageviewer/unionimage/imageutils.cpp
- Added debug and warning logs throughout the image loading and processing functions to improve traceability and error handling.
- Updated .gitignore to exclude .cursor files.
Log: Improve logging for better debugging and exclude unnecessary files from version control.
=> feat: Enhance logging

libimageviewer/unionimage/imgoperate.cpp, libimageviewer/unionimage/pluginbaseutils.cpp, libimageviewer/unionimage/snifferimageformat.cpp, libimageviewer/unionimage/unionimage.cpp, libimageviewer/viewpanel/contents/bottomtoolbar.cpp, libimageviewer/viewpanel/contents/imageinfowidget.cpp, libimageviewer/viewpanel/contents/imgviewlistview.cpp, libimageviewer/viewpanel/contents/imgviewwidget.cpp, libimageviewer/viewpanel/lockwidget.cpp, libimageviewer/viewpanel/navigationwidget.cpp, libimageviewer/viewpanel/scen/graphicsitem.cpp, libimageviewer/viewpanel/scen/imagegraphicsview.cpp, libimageviewer/viewpanel/scen/imagesvgitem.cpp, libimageviewer/viewpanel/thumbnailwidget.cpp, libimageviewer/viewpanel/viewpanel.cpp
- Added extensive debug and warning logs to various image processing and UI components to improve traceability and error handling.
- Updated initialization and destruction logs for widgets and graphics items.
- Enhanced logging for image loading, thumbnail generation, and event handling.
Log: Improve logging for better debugging and maintainability.
=> feat: Enhance logging throughout image processing components

libimageviewer/slideshow/imageanimation.cpp, libimageviewer/unionimage/unionimage.cpp
-- The Next button should clicked double.
-- The last animation not stop and logic return.
Log: fix issue
Bug: https://pms.uniontech.com/bug-view-328371.html
=> fix: [slide-show] The Next button should clicked double.
